#include <metal_stdlib>
using namespace metal;

/* ================================================================
   ROOMS, WAVE 2 (A) — FRACTAL FIELD, FIREWORKS, OIL FILM, MANDALA.
   Single-triangle fragment shaders, one per room, nothing else.

   The same laws that rule Shaders.metal rule here:
   - The ground is the void (#05060e). A room ADDS light onto it; it
     never paints a theme over it. A faint static starfield lies
     under every room so the void is a sky, not a hole.
   - Colours come ONLY from the track's chord (colA/colB/colC). The
     one licensed exception is FIREWORKS, whose stars are real flame
     chemistry — and even those are pulled 25% back toward the chord.
   - phi(x) = 2·atan(x) is the engine's signature fold: an unbounded
     axis brought home to a finite arc. MANDALA wears it.
   - WCAG 2.3.1 is a law: govern_a() caps luminance at every exit so
     additive enthusiasm becomes saturation, never a white strobe;
     the beat is answered as a breath of geometry, not a flash. The
     FRACTAL FIELD exits through rm_fr::govern, the modern governor
     that spends the INK white budget (Shaders.metal's govern()).
   - r32Float is not filterable on the living-room GPUs, so spectrum
     and waveform are read by INTEGER TEXEL and lerped by hand.
   - white is the INK budget: a room's brightest cores scale by it,
     so a drop may blow out where a verse politely will not.
   - ghostStrength is the phantom hand: before shaping, each room
     lets its coordinate drift toward (ghostX, ghostY).
   - roll0..2 are the room's dice, re-dealt on entry — a room never
     shows the same face twice.

   This file is a SELF-CONTAINED translation unit. Every helper wears
   an _a suffix so its symbol never collides with the identically
   shaped helpers in Shaders.metal / Shaders3.metal — except the
   FRACTAL FIELD's, which live in namespace rm_fr, the newer dialect.
   ================================================================ */

constant float PI_A  = 3.14159265359;
constant float TAU_A = 6.28318530718;

// the void ground — #05060e in the linear-ish working space
constant float3 VOID_A = float3(0.019608, 0.023529, 0.054902);

// ---------------------------------------------------------------
// THE FINAL VizUniforms — verbatim, byte-for-byte identical across
// Shaders.metal, Shaders2.metal, Shaders3.metal, Xforms.metal and
// the mirror Swift struct. The first 96 bytes are wave 1 unchanged;
// _pad0 is renamed xformMode (same slot); twelve floats are appended
// after colC to a 144-byte, 16-byte-aligned block; the dance bus (twelve
// more floats, 144..191) follows, stride 192 — asserted under the struct.
// ---------------------------------------------------------------
struct VizUniforms {
    float time; float beatPhase; float barPhase; float energy;      // 0..3
    float bass; float mid; float treble; float calm;                // 4..7
    float onsetEnv; float aspect; float transition; float xformMode;// 8..11  (was _pad0)
    float4 colA; float4 colB; float4 colC;                          // 48 / 64 / 80
    float act; float phrasePhase; float white; float ghostX;        // 96..108
    float ghostY; float ghostStrength; float roll0; float roll1;    // 112..124
    float roll2; float _pad1; float _pad2; float _pad3;             // 128..140
    // _pad1/_pad2 (132/136) carry the LENS pass's live fields and _pad3
    // (140) the song's Camelot number — no pad here is free to claim
    float dHit; float dAge; float dKick; float dMass;               // 144..156  the dance bus (see tools/dance_prelude.mjs)
    float dArtic; float dSpark; float dSway; float dLift;           // 160..172
    float dBrace; float dImpact; float dStill; float dPeriod;       // 176..188  -> stride 192
};
static_assert(sizeof(VizUniforms) == 192, "VizUniforms drifted: the CPU mirror uploads 192 bytes");

// ---------------------------------------------------------------
// helpers (all _a — this file's private ladder)
// ---------------------------------------------------------------

// THE DANCE PRELUDE — the shape helpers a dancing room reads the bus
// (U.dHit … U.dPeriod, bytes 144..191) through, emitted by
// tools/dance_prelude.mjs in suffix mode (_a) so this flat TU keeps its
// one-suffix law; identical in meaning to the web's GLSL_DANCE and to the
// namespace copies in Shaders40/41/42 (node tools/dance_prelude.mjs --check
// refuses drift). Nothing in this unit calls them yet: stage 2 of the dance
// layer makes the bus live but invisible.
// @dance-prelude-begin(suffix,_a)
// THE DANCE BUS - generated by tools/dance_prelude.mjs (node tools/dance_prelude.mjs --write); never edit by hand.
// Accessors: U.dHit ... U.dPeriod (VizUniforms bytes 144..191). Mode: suffix _a.
// 0 at the hit, 1 at the next count - the bar phase, four to the bar
inline float danceBeatPhase_a(constant VizUniforms& U){ return fract(U.barPhase * 4.0); }
// the count's weight: 1 on the one, 0.8 on the three, 0.6 on the two and the four; 0.8 without a bar (freewheel)
inline float danceBeatWeight_a(constant VizUniforms& U){ if (U.dPeriod <= 0.0) return 0.8; float i = floor(U.barPhase * 4.0); return i < 0.5 ? 1.0 : (abs(i - 2.0) < 0.5 ? 0.8 : 0.6); }
// the coil before the beat: loads over the last 40 % of the beat, unloads in the last 35 ms as dKick begins to rise; gated by stillness, 0.4 when freewheeling. Rooms subtract ~20 % of the hit's gain x lean: the form draws back before it moves
inline float danceLean_a(constant VizUniforms& U, float ph){ return U.dStill * (0.6 + 0.4 * U.dStill) * smoothstep(0.60, 0.92, ph) * (1.0 - smoothstep(0.93, 1.0, ph)) * (U.dPeriod > 0.0 ? 1.0 : 0.4); }
// the step: a C1 reshaping of the beat's progress - fastest on the count, dwelling at the half; slope 1 + A*cos >= 0.25 for A <= 0.75, so a walk on it never runs backwards (T += dPeriod * (danceStride(ph, A) - ph))
inline float danceStride_a(float ph, float A){ return ph + (A / 6.2831853) * sin(6.2831853 * ph); }
// a travelling head along x (0 near ... 1 far) that leaves at age 0 and arrives at age 1 - the beat as an event with a place
inline float danceFront_a(float x, float age, float w){ float d = (x - min(age, 1.0)) / w; return exp(-d * d); }
// struck on the hit (the 0.12-beat attack is the body arriving, not a snap), HELD through the fall, released in the last third of the beat; 0 once the beat is over
inline float danceLamp_a(float hit, float age){ return (0.5 + 0.5 * hit) * smoothstep(0.0, 0.12, age) * (1.0 - smoothstep(0.62, 1.0, age)) * step(age, 1.0); }
// the heavy landing (age = dImpact, in beats): a struck mass with period two beats and zeta 0.32 - peak 1 at 0.42 beat, one rebound below rest (-35 %), within 5 % by a bar; 0 for age >= 8 (none)
inline float danceLand_a(float age){ return 1.60729 * exp(-1.00531 * age) * sin(2.97640 * age) * step(0.0, age) * (1.0 - step(8.0, age)); }
// articulation held per bar: a re-sculpt in the first fifth of the bar, then hold - a fold turns once per bar, never 0.04 rad on every snare
inline float danceHeld_a(float barIdx, float barPh, float seed){ float a = fract(sin((barIdx - 1.0) * 12.9898 + seed) * 43758.5453); float b = fract(sin(barIdx * 12.9898 + seed) * 43758.5453); return mix(a, b, smoothstep(0.0, 0.2, barPh)); }
// a struck damped oscillator's PERIODIC steady state from the phase alone (= sum e^{-a(ph+k)} sin(b(ph+k))): a sprung rebound at a fixed place in the beat with no CPU state. a = settle (2.5 ~ 92 % by the next count), b = 2*pi x rebounds
inline float danceRing_a(float ph, float a, float b){ float ea = exp(-a); return exp(-a * ph) * (sin(b * ph) - ea * sin(b * ph - b)) / (1.0 - 2.0 * ea * cos(b) + ea * ea); }
// the breathing law (Shaders.metal's pulse room): a swell with the beat clock, never a flash with it
inline float danceBreath_a(constant VizUniforms& U, float amt){ return 1.0 + amt * cos(danceBeatPhase_a(U) * 6.2831853); }
// @dance-prelude-end

// the signature fold — an infinite axis brought home to (-PI, PI)
inline float phiFold_a(float x) { return 2.0 * atan(x); }

inline float lumaOf_a(float3 c) { return dot(c, float3(0.2126, 0.7152, 0.0722)); }

// the flash governor — luminance capped so overdrive saturates, never strobes
inline float3 govern_a(float3 c) {
    float L = lumaOf_a(c);
    float cap = 0.85;
    return (L > cap) ? c * (cap / L) : c;
}

// sin-dot hashes: scalar, 2->1, 2->2
inline float hash11_a(float x) {
    return fract(sin(x * 12.9898) * 43758.5453123);
}
inline float hash21_a(float2 p) {
    return fract(sin(dot(p, float2(127.1, 311.7))) * 43758.5453123);
}
inline float2 hash22_a(float2 p) {
    float n = sin(dot(p, float2(41.3, 289.1)));
    return fract(float2(262144.0, 32768.0) * n);
}

// value noise -> 4-octave fbm
inline float vnoise_a(float2 p) {
    float2 i = floor(p);
    float2 f = fract(p);
    float2 u = f * f * (3.0 - 2.0 * f);
    float a = hash21_a(i);
    float b = hash21_a(i + float2(1.0, 0.0));
    float c = hash21_a(i + float2(0.0, 1.0));
    float d = hash21_a(i + float2(1.0, 1.0));
    return mix(mix(a, b, u.x), mix(c, d, u.x), u.y);
}

inline float fbm4_a(float2 p) {
    float v = 0.0;
    float a = 0.5;
    for (int i = 0; i < 4; i++) {          // literal-bounded, always four octaves
        v += a * vnoise_a(p);
        p = p * 2.03 + float2(17.7, 9.2);
        a *= 0.5;
    }
    return v;
}

// spectrum: 256x1 r32Float, the FIRST 64 texels carry the bands. Manual lerp.
inline float band64_a(texture2d<float, access::read> t, float u) {
    float fx = clamp(u, 0.0, 1.0) * 63.0;
    uint i0 = (uint)fx;
    uint i1 = min(i0 + 1u, 63u);
    float f = fx - (float)i0;
    return mix(t.read(uint2(i0, 0)).r, t.read(uint2(i1, 0)).r, f);
}

// pixel position -> centered, aspect-true coordinates (y in -1..1)
inline float2 centered_a(float2 pix, float2 res, float aspect) {
    float2 r = max(res, float2(1.0));
    float2 uv = pix / r;
    float2 p = uv * 2.0 - 1.0;
    p.x *= max(aspect, 1e-4);
    return p;
}

// the starfield underlay — two octaves of tiny static hashed points,
// brightness ~0.10-0.25. Returned as a scalar; each room tints it with
// the chord so even the sky obeys the colour law.
inline float starLayer_a(float2 uv) {
    float s = 0.0;
    float2 g = uv * 90.0;
    float2 c = floor(g);
    float h = hash21_a(c);
    float2 f = fract(g) - 0.5;
    s += smoothstep(0.994, 1.0, h) * exp(-dot(f, f) * 42.0) * 0.16;
    g = uv * 165.0 + 23.1;
    c = floor(g);
    h = hash21_a(c + 7.7);
    f = fract(g) - 0.5;
    s += smoothstep(0.997, 1.0, h) * exp(-dot(f, f) * 55.0) * 0.10;
    return s;
}

// the phantom hand — before shaping, a coordinate drifts toward the
// ghost point inside a soft attraction well, scaled by ghostStrength.
inline float2 ghostWarp_a(float2 p, constant VizUniforms& U) {
    float2 g = float2(U.ghostX, U.ghostY);
    float2 d = g - p;
    float pull = U.ghostStrength * 0.35 * exp(-dot(d, d) * 0.8);
    return p + d * pull;
}

// pick one of the three chord stops from a hash — the only colours a
// firework star is allowed to lean into.
inline float3 pickChord_a(constant VizUniforms& U, float h) {
    return (h < 0.34) ? U.colA.rgb : (h < 0.67 ? U.colB.rgb : U.colC.rgb);
}

// ---------------------------------------------------------------
// the one triangle is declared in Shaders.metal (fullscreen_vertex);
// these rooms reuse that vertex stage — no vertex function here.
// ---------------------------------------------------------------

// ---------------------------------------------------------------
// FRACTAL FIELD — three ten-sided dice: the web room, retold.
//
//   FORM d10 x SURFACE d10 x SPACE d10 = 1000 faces, dealt from the
//   room's own dice: face = floor(roll * 10) for roll0 / roll1 / roll2.
//   Every table, distance estimator, glow and constant below is the
//   web's buildFractalField (docs/index.html: FORMS, SURFACES, SPACES,
//   GLSL_FRACTAL, MARCH_FRAG) said in Metal — the parity law holds the
//   two stages to the same thousand faces.
//
//   ONE DE PER FORM. The web compiles one program per form (#define
//   FORM n) so no program carries ten estimators' registers. Here that
//   is a template: formDE<F> and fieldColor<F> are instantiated once
//   per form and ONE switch on the dealt form picks the instance. The
//   die is the same for every pixel of a frame, so the switch never
//   diverges, and each instance holds exactly one estimator.
//
//   SEAM-FREE. The bulb family iterates in spherical coordinates through
//   atan2, whose branch cut on the -x axis is invisible only at INTEGER
//   powers (sin(p·π) = sin(−p·π) only then). The power walk therefore
//   never slides the exponent: it blends two integer-power distance
//   fields — a mix of two 1-Lipschitz bounds is a 1-Lipschitz bound, so
//   the march stays safe — on a ping-pong ladder 9,8,…,3,4,…,9 whose
//   neighbouring rungs differ by exactly one. The box, IFS and Menger
//   forms use no trig, so their scale and twist breathe continuously.
//
//   STATELESS. Everything the web's update() integrates on the CPU is a
//   closed form here, in U.time (the monotone rubato clock), the bands,
//   the onset envelope and the dice: the walk, the c offsets, the box
//   breathing, the julia drift, the vein phase, the orbs, the camera.
//
//   THE PIXEL FOOTPRINT. foot = t × (the angle one pixel spans). The hit
//   test, the normal's tap radius and every level-of-detail cut are
//   measured in it, so relief finer than a pixel merges into its face
//   instead of shimmering as moiré. The footprint counts at most 720
//   lines — the web's 0.6-scale target on a 1080p wall — so the TV
//   resolves the structure the web resolves, in the steps the web takes.
//
//   THE GLOW IS FREE. Three emissions ride inside the one sphere trace,
//   from numbers the march already has: the NEAR-MISS corona (closest
//   approach in px + how hard the ray worked), the HALO (a Lorentzian of
//   the distance integrated in closed form across each step) and the
//   BANDS (the shallow orbit trap wrapped into self-lit veins). A miss
//   lays its glow over the starfield with the alpha the web composites
//   with; a ray that passes nowhere near the set stays sky.
//
//   SOURCES — the mathematics, cited:
//     Mandelbulb — Daniel White and Paul Nylander, 2009
//       (fractalforums.com, "true 3D mandelbrot type fractal").
//     Mandelbox — Tom Lowe ("Tglad"), 2010
//       (fractalforums.com, "amazing fractal").
//     Menger sponge distance and kaleidoscopic IFS — Knighty, 2010
//       (fractalforums.com, "Kaleidoscopic (escape time) IFS").
//     Sierpinski tetrahedron — classical.
//     Orbit traps — Clifford Pickover.
//
//   Every helper of this room lives in namespace rm_fr (the _a ladder
//   above serves the other rooms). The exit is the modern white-budget
//   governor, rm_fr::govern — the web's inkRolloff, knee and bleach.
// ---------------------------------------------------------------
namespace rm_fr {

// ---- die 1: FORM. bound = marching sphere, dist = framing distance,
//      eps = hit radius in pixels. 0 BULB 1 QUARTZ 2 SPIRE 3 CUBE 4 VOID
//      5 SPONGE 6 TETRA 7 JULIA 8 OCTA 9 WEAVE ----
constant float FORM_BOUND[10] = { 1.70, 1.60, 1.85, 8.70, 5.00, 1.95, 2.00, 1.70, 1.60, 2.40 };
constant float FORM_DIST[10]  = { 2.55, 2.45, 2.50, 15.5, 7.60, 3.50, 3.90, 2.60, 3.10, 4.40 };
constant float FORM_EPS[10]   = { 0.5,  0.5,  0.5,  2.0,  0.8,  0.5,  0.6,  0.5,  0.6,  0.6  };

// ---- die 2: SURFACE. 0 EMBER 1 FROST 2 SLATE 3 PEARL 4 CHROME 5 INK
//      6 NEON 7 DUSK 8 BONE 9 PRISM. trap: 0 ORB, 1 PLANE, 2 CROSS.
//      route: 0 A->B, 1 B->C, 2 C->A, 3 A->C. hue is a small bias in
//      radians, never a spin out of the chord ----
constant int   SURF_TRAP[10]  = { 0, 0, 1, 1, 1, 2, 2, 2, 0, 1 };
constant float SURF_SHINE[10] = { 1.0, 0.5, 0.0, 0.5, 1.0, 0.0, 1.0, 0.5, 0.0, 1.0 };
constant int   SURF_LIGHT[10] = { 0, 1, 0, 1, 1, 0, 0, 1, 1, 0 };
constant int   SURF_ROUTE[10] = { 0, 1, 3, 2, 1, 0, 2, 3, 3, 2 };
constant int   SURF_INV[10]   = { 0, 0, 1, 0, 1, 1, 0, 0, 1, 1 };
constant float SURF_HUE[10]   = { 0.00, 0.10, -0.10, 0.05, 0.00, -0.20, 0.20, -0.05, 0.08, 0.25 };
constant float SURF_GLOW[10]  = { 0.55, 0.70, 0.20, 0.45, 0.40, 0.75, 1.00, 0.60, 0.18, 0.85 };
constant float SURF_HALO[10]  = { 0.50, 0.65, 0.12, 0.40, 0.30, 0.85, 1.00, 0.60, 0.12, 0.90 };
constant float SURF_BAND[10]  = { 0.35, 0.25, 0.00, 0.15, 0.20, 0.90, 1.00, 0.40, 0.05, 0.80 };
constant float SURF_BANDK[10] = { 2.0,  1.6,  1.5,  1.2,  2.4,  2.8,  2.4,  1.6,  1.2,  3.6  };
constant float SURF_BODY[10]  = { 1.00, 0.95, 1.00, 1.00, 1.00, 0.40, 0.45, 0.90, 1.00, 0.60 };

// ---- die 3: SPACE. 0 OPEN 1 KALEIDO 2 ORBIT 3 CATHEDRAL 4 LONG 5 CLOSE
//      6 HALL 7 RUSH 8 CHAPEL 9 SWARM. lens is a PERSPECTIVE change, not
//      a zoom: distance is divided by the factor that scales the FOV ----
constant int   SPACE_MIRROR[10] = { 0, 1, 0, 1, 0, 0, 1, 0, 1, 0 };
constant int   SPACE_ORBS[10]   = { 0, 0, 1, 1, 0, 0, 0, 1, 1, 1 };
constant int   SPACE_LENS[10]   = { 1, 1, 1, 1, 0, 2, 0, 2, 0, 2 };
constant float SPACE_ORBMUL[10] = { 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.65, 1.0, 1.9 };
constant float LENS_MUL[3]      = { 0.80, 1.0, 1.25 };

constant float FOOT_LINES = 720.0;   // the footprint's line count ceiling (see THE PIXEL FOOTPRINT)
constant float RUNG_SEC   = 5.0;     // one rung of the power walk, in rubato seconds (the web: 10 beats)
constant float COUPLING   = 0.5;     // the web's pi/e coherence; the TV has no such band — held neutral

// Everything the web feeds its march as uniforms, built once per pixel
// from the closed-form drivers and passed down by reference — nothing at
// program scope is ever written.
struct Params {
    float3 off;                  // uOff: the c offset that keeps every form moving
    float3 juliaC;               // uJuliaC
    float3 orb0, orb1, orb2;     // the three orbiting lamps
    float  orbR;
    float  powA, powB, powT;     // the power walk: two integer powers + their blend
    float  boxScale, boxNorm;    // mandelbox scale; CUBE's size lock
    float  fold;                 // OCTA's twist (radians)
    float  bound, epsPx;
    int    trap, mirror, orbs;
};

// the surface's light, resolved from the chord
struct Look {
    float3 c0, c1, glowCol;
    float  shine, hueAll, glow, halo, band, bandK, body, bandPhase;
    float  energy, beat;
    int    light, inv;
};

// the modern flash governor — Shaders.metal's govern(), the web's inkRolloff:
// the max channel rolls off on a soft knee and the triple rescales by that
// one factor, so hue survives; white must be SPENT from the budget.
inline float3 govern(float3 c, float white) {
    float m = max(c.x, max(c.y, c.z));
    const float K = 0.68;
    if (m <= K) return c;
    float m2 = 1.0 - (1.0 - K) * (1.0 - K) / (m - 2.0 * K + 1.0);
    float3 o = c * (m2 / m);
    float w = clamp(white, 0.0, 1.0);
    if (w <= 0.0) return o;
    float wp = 18.0 + (2.2 - 18.0) * w;
    float t = clamp((m - 1.0) / max(wp - 1.0, 1e-4), 0.0, 1.0);
    t = t * t * (3.0 - 2.0 * t) * w;
    return mix(o, float3(m2), t);
}

// ---- GLSL_FRACTAL, said in Metal ----
inline float trapVal(float3 z, int mode) {
    if (mode == 0) return length(z);                                  // ORB
    if (mode == 1) return min(min(abs(z.x), abs(z.y)), abs(z.z));     // PLANE
    return length(z.xy);                                              // CROSS
}
inline float3 boxFold(float3 z) { return clamp(z, float3(-1.0), float3(1.0)) * 2.0 - z; }
inline void sphereFold(thread float3& z, thread float& dz) {
    float r2 = dot(z, z);
    if (r2 < 0.25) { z *= 4.0; dz *= 4.0; }
    else if (r2 < 1.0) { float t = 1.0 / r2; z *= t; dz *= t; }
}
inline float sdBox(float3 p, float3 b) {
    float3 d = abs(p) - b;
    return min(max(d.x, max(d.y, d.z)), 0.0) + length(max(d, float3(0.0)));
}
// Rodrigues rotation about the grey axis — the web's hueShift
inline float3 hueShift(float3 c, float a) {
    const float3 k = float3(0.57735);
    float ca = cos(a);
    return c * ca + cross(k, c) * sin(a) + k * dot(k, c) * (1.0 - ca);
}
inline bool hitSphere(float3 ro, float3 rd, float rad, thread float& t0, thread float& t1) {
    float b = dot(ro, rd);
    float c = dot(ro, ro) - rad * rad;
    float h = b * b - c;
    if (h < 0.0) return false;
    h = sqrt(h);
    t0 = -b - h; t1 = -b + h;
    return t1 > 0.0;
}
inline float hash12(float2 q) {
    float3 r = fract(float3(q.x, q.y, q.x) * 0.1031);
    r += dot(r, r.yzx + 33.33);
    return fract((r.x + r.y) * r.z);
}
// atan2 refuses (0, 0) under fast math; the origin is a single point of no consequence
inline float atan2s(float y, float x) {
    float xs = x;
    if (abs(x) + abs(y) < 1e-12) xs = 1e-12;
    return atan2(y, xs);
}
// GLSL's mod, floor-based (never fmod, which truncates toward zero)
inline float3 modFloor(float3 x, float y) { return x - y * floor(x / y); }
// the size lock: a scale-s mandelbox (s > 1) fills the cube of half-width H(s)
inline float boxHalf(float s) { return 2.0 * (s + 1.0) / max(s - 1.0, 1e-3); }
// the walk's ladder: rung n -> power, ping-pong 9,8,...,3,4,...,9 (period 12)
inline float rungPower(float n) {
    float m = n - 12.0 * floor((n + 0.5) / 12.0);     // 0..11, robust at the multiples of 12
    return 9.0 - min(m, 12.0 - m);
}
// KIFS level of detail: log2(size / 2 px) folds are resolvable at this footprint
inline float kifsLod(float size, float foot) {
    return clamp(log2(size / max(foot * 2.0, 1e-7)), 0.0, 9.0);
}

// ---- the distance estimators. Each returns the distance and leaves the
//      full orbit trap in `trap` and the SHALLOW trap (first two levels)
//      in `trapE`; both are reset by formDE ----

// One bulb iteration chain at an INTEGER power bp (BULB, QUARTZ, SPIRE, JULIA).
inline float bulbDE(float3 p, float3 cAdd, float bp, int mode,
                    thread float& trap, thread float& trapE) {
    float3 z = p;
    float dr = 1.0;
    float r = 0.0;
    for (int i = 0; i < 8; i++) {
        r = length(z);
        if (r > 2.0) break;
        float rs = max(r, 1e-6);
        float theta = acos(clamp(z.z / rs, -1.0, 1.0)) * bp;
        float phi = atan2s(z.y, z.x) * bp;
        float rp = pow(rs, bp - 1.0);                // r^(bp-1)
        dr = rp * bp * dr + 1.0;
        float zr = rp * rs;                          // r^bp
        float st = sin(theta);
        z = zr * float3(st * cos(phi), st * sin(phi), cos(theta)) + cAdd;
        float tv = trapVal(z, mode);
        trap = min(trap, tv);
        if (i < 2) trapE = min(trapE, tv);
    }
    return 0.5 * log(max(r, 1e-6)) * r / dr;
}

// THE DIMENSIONAL WALK: two integer-power fields, blended. The second is
// evaluated only while the blend is open, so a held rung costs one field.
// The distance, the trap AND the shallow trap are each mixed across the
// walk, never min'd: a min would make the veins and the body tone jump the
// instant a morph opens and closes (the web's formDE, same fix).
inline float deBulbWalk(float3 p, float3 cAdd, thread const Params& P,
                        thread float& trap, thread float& trapE) {
    float d = bulbDE(p, cAdd, P.powA, P.trap, trap, trapE);
    if (P.powT > 0.001) {
        float eA = trapE;
        float eB = 1e10;
        float trapB = 1e10;
        float dB = bulbDE(p, cAdd, P.powB, P.trap, trapB, eB);
        d = mix(d, dB, P.powT);
        trap = mix(trap, trapB, P.powT);
        trapE = mix(eA, eB, P.powT);
    }
    return d;
}

// CUBE / VOID — the mandelbox. q = p·boxNorm is CUBE's size lock (1 for
// VOID); the LOD break stops once |z|/dr, the detail still to resolve, is
// under the hit radius, so sub-pixel crumbs merge into their face.
inline float deBox(float3 p, thread const Params& P, float foot,
                   thread float& trap, thread float& trapE) {
    float3 q = p * P.boxNorm;
    float lim = foot * P.boxNorm * P.epsPx * 0.9;
    float3 z = q;
    float dr = 1.0;
    for (int i = 0; i < 12; i++) {
        z = boxFold(z);
        sphereFold(z, dr);
        z = P.boxScale * z + q + P.off;
        dr = dr * abs(P.boxScale) + 1.0;
        float tv = trapVal(z, P.trap);
        trap = min(trap, tv);
        if (i < 2) trapE = min(trapE, tv);
        float r2 = dot(z, z);
        if (r2 > 400.0 || r2 < lim * lim * dr * dr) break;
    }
    return length(z) / abs(dr) / max(P.boxNorm, 1e-3);
}

// SPONGE — the Menger sponge, four levels
inline float deSponge(float3 p, int mode, thread float& trap, thread float& trapE) {
    float d = sdBox(p, float3(1.0));
    float s = 1.0;
    for (int m = 0; m < 4; m++) {
        float3 a = modFloor(p * s, 2.0) - 1.0;
        s *= 3.0;
        float3 rr = abs(1.0 - 3.0 * abs(a));
        float da = max(rr.x, rr.y), db = max(rr.y, rr.z), dc = max(rr.z, rr.x);
        float c = (min(da, min(db, dc)) - 1.0) / s;
        d = max(d, c);
        float tv = trapVal(a, mode);
        trap = min(trap, tv);
        if (m < 2) trapE = min(trapE, tv);
    }
    return d;
}

// the tetrahedron itself — TETRA's leaf solid
inline float tetLeaf(float3 z) {
    return (max(max(-z.x - z.y - z.z, z.x + z.y - z.z),
                max(-z.x + z.y + z.z, z.x - z.y + z.z)) - 1.0) * 0.57735;
}

// TETRA — the Sierpinski tetrahedron: fold toward the nearest vertex,
// scale 2. A level cut by the LOD reads as a solid tetrahedron, and the
// field fades from level floor(lod) to the next by fract(lod).
inline float deTetra(float3 p, int mode, float foot, thread float& trap, thread float& trapE) {
    float3 z = p;
    const float3 a1 = float3(1.0, 1.0, 1.0);
    const float3 a2 = float3(-1.0, -1.0, 1.0);
    const float3 a3 = float3(1.0, -1.0, -1.0);
    const float3 a4 = float3(-1.0, 1.0, -1.0);
    float lod = kifsLod(2.0, foot);
    float k = 1.0;
    float dPrev = tetLeaf(z);
    float d = dPrev;
    for (int n = 0; n < 9; n++) {
        if (float(n) >= lod) break;
        float3 c = a1;
        float best = dot(z - a1, z - a1);
        float d2 = dot(z - a2, z - a2); if (d2 < best) { c = a2; best = d2; }
        d2 = dot(z - a3, z - a3);       if (d2 < best) { c = a3; best = d2; }
        d2 = dot(z - a4, z - a4);       if (d2 < best) { c = a4; best = d2; }
        z = 2.0 * z - c;
        k *= 0.5;
        float tv = trapVal(z, mode);
        trap = min(trap, tv);
        if (n < 2) trapE = min(trapE, tv);
        float dc = tetLeaf(z) * k;
        d = mix(dPrev, dc, clamp(lod - float(n), 0.0, 1.0));
        dPrev = dc;
    }
    return d;
}

// OCTA — the octahedral kaleidoscopic IFS: abs + sort is the octahedral
// reflection group; a twist of P.fold radians about x (which keeps the
// vertex (1,0,0) fixed), then scale 2 about that vertex — six half-size
// copies per level, each turned further, so the faces spiral.
inline float deOcta(float3 p, thread const Params& P, float foot,
                    thread float& trap, thread float& trapE) {
    const float SZ = 1.25;
    float ca = cos(P.fold), sa = sin(P.fold);
    float3 z = p / SZ;
    float lod = kifsLod(SZ, foot);
    float k = SZ;
    float dPrev = (abs(z.x) + abs(z.y) + abs(z.z) - 1.0) * 0.57735 * k;
    float d = dPrev;
    for (int i = 0; i < 8; i++) {
        if (float(i) >= lod) break;
        z = abs(z);
        float sw;
        if (z.x < z.y) { sw = z.x; z.x = z.y; z.y = sw; }
        if (z.x < z.z) { sw = z.x; z.x = z.z; z.z = sw; }
        if (z.y < z.z) { sw = z.y; z.y = z.z; z.z = sw; }
        float ty = ca * z.y - sa * z.z;
        float tz = sa * z.y + ca * z.z;
        z.y = ty;
        z.z = tz;
        z = z * 2.0 - float3(1.0, 0.0, 0.0);
        k *= 0.5;
        float tv = trapVal(z, P.trap);
        trap = min(trap, tv);
        if (i < 2) trapE = min(trapE, tv);
        float dc = (abs(z.x) + abs(z.y) + abs(z.z) - 1.0) * 0.57735 * k;
        d = mix(dPrev, dc, clamp(lod - float(i), 0.0, 1.0));
        dPrev = dc;
    }
    return d;
}

// WEAVE — a power-3 bulb step and a mandelbox step (box fold, sphere fold,
// scale ~ -1.5) alternate, five of each: the bulb's shells and the box's
// folds interlace into a cage of woven rings around a rose-window core.
inline float deWeave(float3 p, thread const Params& P, thread float& trap, thread float& trapE) {
    float3 z = p;
    float dr = 1.0;
    float r = length(z);
    for (int i = 0; i < 5; i++) {
        float rs = max(r, 1e-6);
        float theta = acos(clamp(z.z / rs, -1.0, 1.0)) * 3.0;
        float phi = atan2s(z.y, z.x) * 3.0;
        dr = 3.0 * r * r * dr + 1.0;
        float st = sin(theta);
        z = (r * r * r) * float3(st * cos(phi), st * sin(phi), cos(theta)) + p + P.off;
        float tv = trapVal(z, P.trap);
        trap = min(trap, tv);
        if (i < 1) trapE = min(trapE, tv);
        r = length(z);
        if (r > 64.0) break;
        z = boxFold(z);
        sphereFold(z, dr);
        z = P.boxScale * z + p + P.off;
        dr = dr * abs(P.boxScale) + 1.0;
        tv = trapVal(z, P.trap);
        trap = min(trap, tv);
        if (i < 1) trapE = min(trapE, tv);
        r = length(z);
        if (r > 64.0) break;
    }
    return 0.5 * log(max(r, 1e-6)) * r / dr;
}

// formDE<F>: F is a compile-time constant, so every test below folds and
// each instance keeps exactly one estimator — the web's #define FORM n.
template <int F>
inline float formDE(float3 p, thread const Params& P, float foot,
                    thread float& trap, thread float& trapE) {
    trap = 1e10;
    trapE = 1e10;
    if (F == 0 || F == 1 || F == 2) return deBulbWalk(p, p + P.off, P, trap, trapE);
    if (F == 7) return deBulbWalk(p, P.juliaC, P, trap, trapE);
    if (F == 3 || F == 4) return deBox(p, P, foot, trap, trapE);
    if (F == 5) return deSponge(p, P.trap, trap, trapE);
    if (F == 6) return deTetra(p, P.trap, foot, trap, trapE);
    if (F == 8) return deOcta(p, P, foot, trap, trapE);
    return deWeave(p, P, trap, trapE);
}

inline float deOrbs(float3 p, thread const Params& P) {
    float d = length(p - P.orb0);
    d = min(d, length(p - P.orb1));
    d = min(d, length(p - P.orb2));
    return d - P.orbR;
}

// the scene: MIRROR folds the sample point (abs() is a reflection — an
// isometry — so the bound stays exact); the orbs are unioned unmirrored.
// .y is the material: 0 the form, 1 an orb.
template <int F>
inline float2 mapScene(float3 p, thread const Params& P, float foot,
                       thread float& trap, thread float& trapE) {
    float3 q = (P.mirror != 0) ? abs(p) : p;
    float df = formDE<F>(q, P, foot, trap, trapE);
    if (P.orbs != 0) {
        float d2 = deOrbs(p, P);
        if (d2 < df) return float2(d2, 1.0);
    }
    return float2(df, 0.0);
}

// the mirror spaces' reflection: a chord sky with a sparse glint lattice
inline float3 envCol(float3 d, constant VizUniforms& U) {
    float y = d.y * 0.5 + 0.5;
    float3 c = mix(U.colB.rgb * 0.10, U.colA.rgb * 0.35, y);
    float s = max(0.0, sin(d.x * 30.0) * sin(d.z * 30.0) * sin(d.y * 30.0));
    float s2 = s * s, s4 = s2 * s2, s8 = s4 * s4, s16 = s8 * s8, s32 = s16 * s16;
    return c + U.colC.rgb * (s32 * s8 * 0.5);            // s^40, by squaring
}

// fieldColor<F>: the web's MARCH_FRAG main() for one form — the sphere
// trace with its three glows, then the hit's shading. Returns the light
// this pixel adds over the void (the sky passed in already includes the
// stars); the caller grains and governs it.
template <int F>
inline float3 fieldColor(float3 ro, float3 rd, float pixAng, float2 fragXY,
                         thread const Params& P, thread const Look& L,
                         constant VizUniforms& U, float3 sky) {
    float t0 = 0.0, t1 = 0.0;
    if (!hitSphere(ro, rd, P.bound, t0, t1)) return sky;

    float t = max(t0, 0.0);
    float tc = length(ro);                      // the camera's distance to the subject's centre
    // HALO — the Lorentzian L(x) = F/(x^2 + F^2) of the distance, integrated
    // over each step in closed form: s·(atan(dB/F) − atan(dA/F))/(dB − dA).
    // L at 5F is taken off so the halo ends there instead of fogging the sphere.
    float HF = P.bound * 0.012;
    float Lcut = 1.0 / (26.0 * HF);
    // the first step is shortened by a per-pixel hash (stepping short is
    // always safe), so neighbouring rays never step in lockstep
    float jit = 0.55 + 0.45 * hash12(fragXY);
    float hitTrap = 1.0, matId = 0.0, minPx = 1e4;
    float dA = 0.0, aA = 0.0, sA = 0.0;
    float3 halo = float3(0.0);
    int steps = 0;
    bool hit = false;
    for (int i = 0; i < 96; i++) {              // literal bound — the web's 96-step budget
        float3 p = ro + rd * t;
        float foot = max(t, 0.001) * pixAng;
        float tr = 1e10, te = 1e10;
        float2 m = mapScene<F>(p, P, foot, tr, te);
        float d = m.x;
        hitTrap = tr;
        steps = i;
        minPx = min(minPx, d / foot);
        float dB = max(d, 0.0);
        float aB = atan(dB / HF);
        if (i > 0) {
            float dd = dB - dA;
            float seg = ((abs(dd) > 1e-4 * HF) ? sA * (aB - aA) / dd
                                               : sA * HF / (dB * dB + HF * HF)) - sA * Lcut;
            if (seg > 0.0) {
                // faded past the subject's middle, so the far side never veils
                // the near, and to nothing at the marching sphere's edge
                float fade = exp(-max(t - tc + 0.3 * P.bound, 0.0) / (0.7 * P.bound))
                           * (1.0 - smoothstep(0.8 * P.bound, P.bound, length(p)));
                halo += L.glowCol * ((0.75 + 0.5 * clamp(tr, 0.0, 1.0)) * seg * fade);
            }
        }
        if (d < P.epsPx * foot) { hit = true; matId = m.y; break; }
        sA = (i == 0) ? d * jit : d;
        dA = dB;
        aA = aB;
        t += sA;
        if (t > t1) break;
    }

    // NEAR-MISS corona: closest approach in pixels + how hard the ray worked
    float sg = float(steps) / 96.0;
    float corona = L.glow * (0.6 * exp(-minPx * 0.2) + 0.45 * sg * sg);
    // the halo is gathered linear and compressed once, softly, here
    float3 hg = halo * (L.halo * 0.10);
    hg /= 1.0 + max(max(hg.r, hg.g), hg.b);

    if (!hit) {
        // the web writes (g/a, a) and composites it over the stars:
        // g + stars·(1 − a). The alpha is the governed glow's, as there; the
        // light itself goes out raw so the exit governs it exactly once.
        float3 g = hg + L.glowCol * (corona * 0.2);
        g *= 0.8 + L.energy * 0.3 + L.beat * 0.15;
        float3 gg = govern(g, U.white);
        float a = clamp(max(max(gg.r, gg.g), gg.b) * 1.5, 0.0, 1.0);
        if (a < 0.004) return sky;
        return g + sky * (1.0 - a);
    }

    float3 p = ro + rd * t;
    float foot = max(t, 0.001) * pixAng;
    // the four tetrahedral taps, at about a pixel's footprint so relief finer
    // than a pixel cannot alias the normal; the same taps read the shallow
    // trap — their mean is its box filter, sum(k·trap)/(4e) its gradient,
    // which is what the veins anti-alias with (no screen-space derivatives)
    float e = foot * (0.5 + P.epsPx);
    float3 nn = float3(0.0);
    float3 tg = float3(0.0);
    float tn = 0.0;
    for (int j = 0; j < 4; j++) {
        float3 k = (j == 0) ? float3(1.0, -1.0, -1.0)
                 : ((j == 1) ? float3(-1.0, -1.0, 1.0)
                 : ((j == 2) ? float3(-1.0, 1.0, -1.0)
                 :             float3(1.0, 1.0, 1.0)));
        float trj = 1e10, tej = 1e10;
        float dj = mapScene<F>(p + k * e, P, foot, trj, tej).x;
        tej = min(tej, 1e4);                    // an escaped tap's 1e10 stays finite in the gradient
        nn += k * dj;
        tn += tej;
        tg += k * tej;
    }
    float trapN = 0.25 * tn;
    float3 trapG = tg / (4.0 * e);
    float nl = dot(nn, nn);
    float3 n = (nl > 1e-24) ? nn * rsqrt(nl) : -rd;
    float ndv = clamp(dot(n, -rd), 0.0, 1.0);
    float omn = 1.0 - ndv;

    if (matId > 0.5) {
        // the orbs are lamps: a dim core and a bright limb, like a lit bubble
        float3 oc = mix(U.colC.rgb, U.colB.rgb, 0.35) * (1.0 + L.beat * 0.6);
        return oc * (0.22 + ndv * 0.28 + omn * omn * 1.25) + hg * 0.5;
    }

    // the body ramps on two traps — the full one (fine texture) and the
    // shallow one (broad regions) — so the pair reads as two tones
    float trv = mix(1.0 - exp(-2.0 * hitTrap), 1.0 - exp(-1.5 * trapN), 0.5);
    if (L.inv != 0) trv = 1.0 - trv;
    float3 col = mix(L.c0, L.c1, trv);
    float omt = 1.0 - trv;
    col = mix(col, U.colC.rgb, omt * omt * omt * 0.5);
    col = hueShift(col, L.hueAll);

    float3 L1 = normalize(float3(0.6, 0.8, 0.4));
    float d1 = clamp(dot(n, L1), 0.0, 1.0);
    float3 lit;
    if (L.light == 0) {
        lit = col * (0.18 + d1 * 0.9);
    } else {
        float3 L2 = normalize(float3(-0.7, 0.25, -0.55));
        float d2 = clamp(dot(n, L2), 0.0, 1.0);
        lit = col * (0.12 + d1 * 0.62) + U.colB.rgb * (d2 * 0.30 * (0.5 + COUPLING));
    }

    float specPow = mix(10.0, 110.0, L.shine);
    float specAmt = mix(0.10, 1.05, L.shine);
    float spec = pow(clamp(dot(reflect(-L1, n), -rd), 1e-6, 1.0), specPow);
    float ao = 1.0 - sg;
    float fres = omn * omn * omn;

    float3 outc = lit * ((0.35 + ao * 0.75) * L.body);
    outc += U.colC.rgb * (spec * specAmt);
    outc += col * (fres * (0.45 + L.beat * 0.8));
    if (P.mirror != 0) outc = mix(outc, envCol(reflect(rd, n), U), 0.18 + L.shine * 0.32);
    outc *= 0.85 + L.energy * 0.5;

    // BANDS — the shallow trap at the hit (filtered over the taps), wrapped
    // into narrow self-lit veins; fw = how far the vein coordinate moves per
    // pixel, which widens a vein that would fall under a pixel and fades the
    // veins where even that would alias
    float bx = clamp(trapN, 0.0, 4.0) * L.bandK + L.bandPhase;
    float fw = length(trapG) * foot * L.bandK;
    float bs = abs(fract(bx) - 0.5);
    float bw = 0.09;
    float bwe = sqrt(bw * bw + 0.25 * fw * fw);
    float vein = exp(-bs * bs / (bwe * bwe)) * (bw / bwe) * (1.0 - smoothstep(0.2, 0.5, fw));
    // self-lit, in the pair's saturated member (the glow colour), so they read
    float3 veinCol = hueShift(L.glowCol, L.hueAll);
    outc += veinCol * (vein * L.band * (1.0 + L.energy * 0.35 + L.beat * 0.25) * (0.6 + 0.4 * ao));
    // the light the ray gathered on its way in, and a corona on the limb
    outc += hg * (omn * omn * 0.7);
    outc += L.glowCol * (corona * fres * 0.5);

    float fog = 1.0 - clamp((t - t0) / (P.bound * 2.0), 0.0, 1.0);
    return outc * (0.35 + fog * 0.65);
}

}  // namespace rm_fr

fragment float4 room_fractal(float4 pos [[position]],
                             constant VizUniforms& U [[buffer(0)]],
                             constant float2& res [[buffer(1)]],
                             texture2d<float, access::read> spectrum [[texture(0)]],
                             texture2d<float, access::read> waveform [[texture(1)]])
{
    using namespace rm_fr;
    float2 uv = pos.xy / max(res, float2(1.0));
    float2 p = centered_a(pos.xy, res, U.aspect);
    p = ghostWarp_a(p, U);                          // the phantom leans the camera
    float2 sp = float2(p.x, -p.y);                  // y up, as the web's vUv

    // ---- the three dice ----
    int form  = clamp(int(U.roll0 * 10.0), 0, 9);
    int surf  = clamp(int(U.roll1 * 10.0), 0, 9);
    int space = clamp(int(U.roll2 * 10.0), 0, 9);

    float T = U.time;
    float bass = U.bass, mid = U.mid, treble = U.treble;
    float energy = U.energy, beat = U.onsetEnv;

    // ---- apply(): the faces' constants ----
    Params P;
    P.bound = FORM_BOUND[form];
    P.epsPx = FORM_EPS[form];
    P.trap = SURF_TRAP[surf];
    P.mirror = SPACE_MIRROR[space];
    P.orbs = SPACE_ORBS[space];
    P.boxScale = 2.5;
    P.boxNorm = 1.0;
    P.fold = 0.22;

    // ---- update(), in closed form ----
    // THE DIMENSIONAL WALK: a rung every RUNG_SEC rubato seconds, held for
    // 80% of it, the last 20% a smoothstep blend into the next rung. Each
    // bulb form's ladder is phased so its clock's zero sits on its home rung
    // (BULB / JULIA 8 going down, QUARTZ 4 and SPIRE 3 going up).
    P.powA = 8.0;
    P.powB = 8.0;
    P.powT = 0.0;
    if (form <= 2 || form == 7) {
        float home = (form == 1) ? 7.0 : ((form == 2) ? 6.0 : 1.0);
        float wc = T / RUNG_SEC + home;
        float rung = floor(wc);
        P.powA = rungPower(rung);
        P.powB = rungPower(rung + 1.0);
        P.powT = smoothstep(0.8, 1.0, wc - rung);
    }

    float3 off = float3(sin(T * 0.11) * 0.055 + bass * 0.05,
                        cos(T * 0.09) * 0.055 + mid * 0.04,
                        sin(T * 0.07 + 1.7) * 0.055 + treble * 0.03);
    if (form == 3 || form == 4) {
        // box forms: no branch cut, so the scale can breathe; CUBE keeps its
        // outline by sampling at q = p·H(s)/H(2.5)
        off *= 0.6;
        float b = (form == 4) ? -2.2 : 2.5;
        float sgn = (b < 0.0) ? -1.0 : 1.0;
        float s = b + sgn * (sin(T * 0.06) * 0.22 + bass * 0.14 + COUPLING * 0.10);
        P.boxScale = s;
        P.boxNorm = (form == 3) ? boxHalf(s) / boxHalf(2.5) : 1.0;
    } else if (form == 9) {
        off *= 0.5;                                 // WEAVE: the hybrid's box half breathes a little
        P.boxScale = -1.5 - (sin(T * 0.05) * 0.05 + bass * 0.04);
    } else if (form == 8) {
        P.fold = 0.22 + sin(T * 0.07) * 0.06 + mid * 0.05;   // OCTA: the twist breathes with the mids
    }
    P.off = off;
    // JULIA: |c| ~ 0.95 keeps it an open cage of branches
    P.juliaC = float3(0.62 + sin(T * 0.08) * 0.07 + bass * 0.03,
                      0.62 + cos(T * 0.06) * 0.07 + mid * 0.03,
                      -0.28 + sin(T * 0.05 + 2.2) * 0.07 + treble * 0.03);

    // the orbs (only read when the space has them)
    float R = P.bound * 0.78;
    float osc = 1.0 + beat * 0.12;
    P.orb0 = float3(cos(T * 0.50) * R, sin(T * 0.37) * R * 0.5, sin(T * 0.50) * R) * osc;
    P.orb1 = float3(cos(T * 0.31 + 2.1) * R * 0.8, cos(T * 0.43) * R * 0.6, sin(T * 0.31 + 2.1) * R * 0.8) * osc;
    P.orb2 = float3(sin(T * 0.23 + 4.2) * R * 0.9, sin(T * 0.29 + 1.0) * R * 0.45, cos(T * 0.23 + 4.2) * R * 0.9) * osc;
    P.orbR = P.bound * 0.062 * SPACE_ORBMUL[space] * (1.0 + beat * 0.35);

    // ---- the camera. LENS as perspective, not zoom: distance divided by the
    //      factor that scales the FOV, so framing holds and only the
    //      compression changes. The web's camera dollies in on the bass and
    //      breathes its FOV with it. Its wandering orbit is retold as a slow
    //      closed-form pendulum, phased by the dice so a re-entry is a new
    //      angle, that swings ±72° about the key light's azimuth (L1 lies at
    //      atan2(0.4, 0.6) = 0.588 rad in xz) and rides a little above the
    //      equator, so the camera never parks on the form's unlit side ----
    float lensMul = LENS_MUL[SPACE_LENS[space]];
    float base = FORM_DIST[form] / lensMul;
    float D = base - bass * (base * 0.07) - beat * (base * 0.024) + sin(T * 0.05) * (base * 0.05);
    float camR = max(P.bound * 1.14, D);
    float az0 = fract(U.roll0 * 31.7 + U.roll1 * 17.3 + U.roll2 * 7.1) * TAU_A;
    float theta = 0.588 + 1.25 * sin(T * 0.035 + az0);
    float polar = 1.30 + 0.45 * sin(T * 0.021 + 1.3 * az0);          // from +y, as the web's camPhi
    float3 dir = normalize(float3(sin(polar) * cos(theta), cos(polar) * 0.6, sin(polar) * sin(theta)));
    float3 ro = dir * camR;
    float3 fwd = -dir;
    float3 right = normalize(cross(fwd, float3(0.0, 1.0, 0.0)));
    float3 up = cross(right, fwd);
    float tanFov = tan((31.0 + 4.0 * bass) * (PI_A / 180.0)) * lensMul;   // 62° + 8°·bass, full angle
    float3 rd = normalize(fwd + (right * sp.x + up * sp.y) * tanFov);
    float pixAng = 2.0 * tanFov / min(max(res.y, 1.0), FOOT_LINES);   // the angle one pixel spans

    // ---- the surface's light, routed through a pair of chord colours ----
    int route = SURF_ROUTE[surf];
    float3 cA = U.colA.rgb, cB = U.colB.rgb, cC = U.colC.rgb;
    Look L;
    L.c0 = (route == 1) ? cB : ((route == 2) ? cC : cA);
    L.c1 = (route == 0) ? cB : ((route == 2) ? cA : cC);
    // the light the structure gives off is the pair's saturated member —
    // never the chord's pale third (colC), which would read as fog
    L.glowCol = (route == 1 || route == 3) ? L.c0 : L.c1;
    L.shine = SURF_SHINE[surf];
    L.light = SURF_LIGHT[surf];
    L.inv = SURF_INV[surf];
    // the web's uHue (spectral centroid + coupling) has no TV band; the
    // treble-over-bass tilt stands in for the centroid, coupling held neutral
    float hueDrift = 0.125 + 0.20 * (treble - bass);
    L.hueAll = hueDrift * 0.7 + SURF_HUE[surf];
    L.glow = SURF_GLOW[surf];
    L.halo = SURF_HALO[surf];
    L.band = SURF_BAND[surf];
    L.bandK = SURF_BANDK[surf];
    L.body = SURF_BODY[surf];
    // the veins' phase flows with the music: the web advances it at
    // (0.035 + 0.11·energy)/s, which is ~0.09 per rubato second at any energy
    L.bandPhase = fract(T * 0.09);
    L.energy = energy;
    L.beat = beat;

    // the void sky: the static starfield, tinted by the chord
    float3 sky = starLayer_a(uv) * mix(float3(0.75), cC, 0.55);

    // ---- ONE switch: the dealt form's instance, and only it, runs ----
    float3 col;
    switch (form) {
        case 0:  col = fieldColor<0>(ro, rd, pixAng, pos.xy, P, L, U, sky); break;
        case 1:  col = fieldColor<1>(ro, rd, pixAng, pos.xy, P, L, U, sky); break;
        case 2:  col = fieldColor<2>(ro, rd, pixAng, pos.xy, P, L, U, sky); break;
        case 3:  col = fieldColor<3>(ro, rd, pixAng, pos.xy, P, L, U, sky); break;
        case 4:  col = fieldColor<4>(ro, rd, pixAng, pos.xy, P, L, U, sky); break;
        case 5:  col = fieldColor<5>(ro, rd, pixAng, pos.xy, P, L, U, sky); break;
        case 6:  col = fieldColor<6>(ro, rd, pixAng, pos.xy, P, L, U, sky); break;
        case 7:  col = fieldColor<7>(ro, rd, pixAng, pos.xy, P, L, U, sky); break;
        case 8:  col = fieldColor<8>(ro, rd, pixAng, pos.xy, P, L, U, sky); break;
        default: col = fieldColor<9>(ro, rd, pixAng, pos.xy, P, L, U, sky); break;
    }

    col += (hash21_a(pos.xy) - 0.5) * 0.004;         // grain against banding
    return float4(rm_fr::govern(VOID_A + max(col, float3(0.0)), U.white), 1.0);
}

// ---------------------------------------------------------------
// FIREWORKS — stateless closed-form ballistics. Up to eight shells are
// alive at once, each identified by hash(launchBar, slot); nothing is
// remembered between frames, so every shell is reconstructed from the
// clock alone.
//
// THE TRICK: lift time is exactly one bar. A shell launches on a
// downbeat and BURSTS on the next downbeat, so the break lands on the
// bar. The integer bar index only sets identity (a nominal cadence);
// the sub-bar timing is the true barPhase, so the landing is exact
// even if the identity clock drifts.
//
// Fire density follows the act: the overture fires singles, the apex
// fires salvos. Star colours are flame chemistry — commented with the
// emitting species — pulled 25% back toward the chord. Willow shells
// carry high drag and long trail smear; the stars are integrated in
// closed form (linear drag + gravity) from the shell's age.
// ---------------------------------------------------------------
fragment float4 room_pyro(float4 pos [[position]],
                          constant VizUniforms& U [[buffer(0)]],
                          constant float2& res [[buffer(1)]],
                          texture2d<float, access::read> spectrum [[texture(0)]],
                          texture2d<float, access::read> waveform [[texture(1)]])
{
    float2 uv = pos.xy / max(res, float2(1.0));
    float2 p = centered_a(pos.xy, res, U.aspect);
    p = ghostWarp_a(p, U);

    float3 col = starLayer_a(uv) * mix(float3(0.7), U.colC.rgb, 0.5);

    // the bar clock: integer part for identity (nominal), fractional part
    // locked to the real downbeat via barPhase so breaks land on the bar.
    float barLen = 1.9;                              // nominal seconds/bar (identity only)
    float barNo = floor(U.time / barLen);
    float bc = barNo + U.barPhase;                   // continuous bar coordinate

    // flame chemistry — fixed emission colours by species
    const float3 SP_STRONTIUM = float3(0.95, 0.10, 0.12); // strontium  red    ~650 nm
    const float3 SP_SODIUM    = float3(1.00, 0.78, 0.20); // sodium     yellow ~589 nm
    const float3 SP_BARIUM    = float3(0.35, 0.95, 0.40); // barium     green  ~515 nm
    const float3 SP_COPPER    = float3(0.25, 0.45, 0.98); // copper     blue   ~452 nm
    const float3 SP_CHARCOAL  = float3(1.00, 0.55, 0.15); // charcoal   gold   ~1750 K

    for (int b = 0; b < 4; b++) {                    // the four most recent bars of launches
        float launchBar = barNo - float(b);
        for (int s = 0; s < 2; s++) {                // up to two shells (slots) per bar
            float2 hh = hash22_a(float2(launchBar * 3.7 + 11.0, float(s) * 5.1 + 2.0));
            // density by act: slot 0 nearly always fires; slot 1 only as the
            // act rises (overture singles -> apex salvos, act in 0..4).
            float actGate = (s == 0) ? 0.15 : (0.62 - 0.12 * U.act);
            if (hh.x < actGate) continue;

            float age = bc - launchBar;              // bars since launch
            if (age < 0.0 || age > 2.4) continue;    // outside its living window

            // launch + apex geometry from the shell's hash
            float lx = (hh.y - 0.5) * 1.7;
            float apexX = lx + (hash21_a(float2(launchBar, float(s) + 7.0)) - 0.5) * 0.4;
            float apexY = 0.15 + hash21_a(float2(launchBar * 1.3, float(s) * 2.1 + 3.0)) * 0.55;
            float2 launchP = float2(lx, -0.95);
            float2 apex = float2(apexX, apexY);

            if (age < 1.0) {
                // RISING — a decelerating comet climbs launch -> apex, a
                // bright head trailing a thin tail below it.
                float e = 1.0 - (1.0 - age) * (1.0 - age);   // ease toward the apex
                float2 cpos = mix(launchP, apex, e);
                float2 dd = p - cpos;
                float head = exp(-dot(dd, dd) * 900.0);
                float2 tv = normalize(apex - launchP + float2(1e-4));
                float along = dot(dd, tv);
                float2 perp = dd - tv * along;
                float trail = exp(-dot(perp, perp) * 1600.0) * exp(min(along, 0.0) * 7.0) * step(along, 0.0);
                float3 sc = mix(SP_CHARCOAL, pickChord_a(U, hh.x), 0.25);   // gold rising spark
                col += sc * (head * 0.9 + trail * 0.35) * (0.6 + 0.4 * U.white);
            } else {
                // BURST — closed-form ballistic stars from the apex.
                float ageS = (age - 1.0) * barLen;   // seconds since the break
                float shellFade = exp(-ageS * 1.1);
                if (shellFade < 0.02) continue;

                float willow = hash21_a(float2(launchBar + 2.0, float(s) + 4.0));
                float k = mix(0.9, 3.2, willow);     // linear drag; willow shells drag hard
                float g = 1.6;                       // gravity
                float speed = 0.55 + 0.35 * hash21_a(float2(launchBar + 5.0, float(s)));
                int starCount = 24 + int(hash21_a(float2(launchBar, float(s) + 9.0)) * 40.0); // 24..64

                float sp = hash21_a(float2(launchBar + 8.0, float(s) + 1.0));
                float3 species;
                if      (sp < 0.20) species = SP_STRONTIUM;
                else if (sp < 0.40) species = SP_SODIUM;
                else if (sp < 0.60) species = SP_BARIUM;
                else if (sp < 0.80) species = SP_COPPER;
                else                species = SP_CHARCOAL;
                float3 starCol = mix(species, pickChord_a(U, sp), 0.25);   // 25% toward the chord

                float2 vinf = float2(0.0, -g) / k;   // terminal velocity under drag + gravity
                float ed = (1.0 - exp(-k * ageS)) / k;   // shared drag integral

                for (int j = 0; j < 64; j++) {       // literal bound; only starCount draw
                    if (j >= starCount) break;
                    float fj = float(j);
                    float ang = (fj + 0.5) / float(starCount) * TAU_A
                              + hash21_a(float2(launchBar * 7.0 + fj, float(s))) * 0.15;
                    float spj = speed * (0.8 + 0.4 * hash21_a(float2(fj, launchBar + float(s))));
                    float2 v0 = float2(cos(ang), sin(ang)) * spj;
                    // x(t) = vinf*t + (v0 - vinf)*(1 - e^{-kt})/k
                    float2 spos = apex + vinf * ageS + (v0 - vinf) * ed;
                    float2 dd = p - spos;
                    float d2 = dot(dd, dd);
                    float2 vel = vinf + (v0 - vinf) * exp(-k * ageS);
                    float2 vd = normalize(vel + float2(1e-4));
                    float par = dot(dd, vd);
                    float2 pe = dd - vd * par;
                    float peL = dot(pe, pe);
                    float body = exp(-d2 * 5000.0);
                    float smear = exp(-peL * 6000.0)
                                * ((par < 0.0) ? exp(par * 24.0) : exp(-par * par * 9000.0));
                    float bright = (body + 0.5 * smear * (0.5 + willow)) * shellFade;
                    col += starCol * bright * (0.5 + 0.7 * U.white);   // the burst is the core
                }
            }
        }
    }

    col += (hash21_a(pos.xy) - 0.5) * 0.004;
    return float4(govern_a(VOID_A + max(col, float3(0.0))), 1.0);
}

// ---------------------------------------------------------------
// OIL FILM — thin-film interference on a drifting slick. The thickness
// field is fbm warped by fbm (two nested domain warps, four octaves);
// the low end THICKENS the film, so every colour walks when the bass
// moves. Interference is sin² fringes evaluated at three wavelengths
// (610/545/465 nm scale factors) mapped to RGB, then leaned 40% toward
// the chord. Every onset drops one expanding ripple ring from a
// roll-picked point, distorting the film as it passes; the treble
// catches the fringe crests as sparkle.
// ---------------------------------------------------------------
fragment float4 room_oilfilm(float4 pos [[position]],
                             constant VizUniforms& U [[buffer(0)]],
                             constant float2& res [[buffer(1)]],
                             texture2d<float, access::read> spectrum [[texture(0)]],
                             texture2d<float, access::read> waveform [[texture(1)]])
{
    float2 uv = pos.xy / max(res, float2(1.0));
    float2 p = centered_a(pos.xy, res, U.aspect);
    p = ghostWarp_a(p, U);

    float t = U.time * 0.05;
    float2 q = p * (1.6 + 0.2 * U.roll0);

    // two nested domain warps — fbm displacing fbm
    float2 w1 = q + float2(fbm4_a(q + float2(t, -t)),
                           fbm4_a(q + float2(5.2, 1.3) - t));
    float2 w2 = w1 * 1.7 + float2(fbm4_a(w1 * 1.4 + float2(t * 0.6, 2.1)),
                                  fbm4_a(w1 * 1.4 + float2(-3.3, t * 0.4)));
    float thick = fbm4_a(w2 * 1.2);

    // the low end thickens the film — the whole slick walks with the bass
    thick = thick * (1.0 + 0.9 * U.bass) + 0.25 * U.bass;

    // the onset ripple ring: one ring per onset, expanding as the envelope
    // decays and fading as it grows, dropped from a roll-picked point.
    float2 rc = float2(U.roll1 * 2.0 - 1.0, U.roll2 * 2.0 - 1.0) * 0.6;
    float rdist = length(p - rc);
    float ringR = (1.0 - U.onsetEnv) * 1.6;
    float ring = exp(-(rdist - ringR) * (rdist - ringR) * 40.0) * U.onsetEnv;
    thick += ring * 0.5 * sin((rdist - ringR) * 26.0);   // the ripple bends the fringes

    // interference: sin² fringes at three wavelengths -> RGB
    float freq = 16.0 + 8.0 * U.bass;
    float ph = thick * freq;
    float kr = 545.0 / 610.0;      // red — the slow fringe
    float kg = 1.0;                // green — the reference (545 nm)
    float kb = 545.0 / 465.0;      // blue — the fast fringe
    float sr = sin(ph * kr);
    float sg = sin(ph * kg);
    float sb = sin(ph * kb);
    float3 fr = float3(sr * sr, sg * sg, sb * sb);

    // leaned 40% toward the chord (thickness chooses the chord stop)
    float3 chord = mix(U.colA.rgb, U.colC.rgb, clamp(thick, 0.0, 1.0));
    chord = mix(chord, U.colB.rgb, 0.35 * U.mid);
    float3 film = mix(fr, chord * (0.35 + 0.75 * (fr.r + fr.g + fr.b) / 3.0), 0.40);

    float vign = exp(-dot(p, p) * 0.35);
    float3 col = film * (0.35 + 0.40 * U.energy) * vign;

    // the ripple's own bright crest — a core, so the INK budget rides it
    col += U.colC.rgb * ring * 0.40 * (0.5 + 0.7 * U.white);

    // treble sparkle catching the fringe crests
    float crest = smoothstep(0.75, 1.0, sr * sr);
    float2 scell = floor(p * 120.0);
    float spk = smoothstep(0.985, 1.0, hash21_a(scell + floor(U.time * 6.0)));
    col += U.colC.rgb * spk * crest * U.treble * (0.4 + 0.9 * U.white);

    // the void sky bleeds through the thin regions of the slick
    col += starLayer_a(uv) * mix(float3(0.7), U.colC.rgb, 0.5) * (1.0 - clamp(thick, 0.0, 1.0) * 0.7);

    col += (hash21_a(pos.xy) - 0.5) * 0.004;
    return float4(govern_a(VOID_A + max(col, float3(0.0))), 1.0);
}

// ---------------------------------------------------------------
// MANDALA — a kaleidoscope. The angle folds into k mirrored sectors
// (k = 6 + floor(roll0*6)*2, even, 6..16); petal rings sit at phi-folded
// radii so the infinite radial axis fits a finite bloom. The palette is
// five hard-quantized colours — the chord plus two darkened variants —
// separated by dark seams (the cell5 look), never a wash. Tip lamps at
// the petal ends answer the onset. The whole figure turns slowly
// (time*0.03) with a bar-locked micro-turn.
// ---------------------------------------------------------------
fragment float4 room_mandala(float4 pos [[position]],
                             constant VizUniforms& U [[buffer(0)]],
                             constant float2& res [[buffer(1)]],
                             texture2d<float, access::read> spectrum [[texture(0)]],
                             texture2d<float, access::read> waveform [[texture(1)]])
{
    float2 uv = pos.xy / max(res, float2(1.0));
    float2 p = centered_a(pos.xy, res, U.aspect);
    p = ghostWarp_a(p, U);

    // slow spin + a bar micro-turn
    float rot = U.time * 0.03 + U.barPhase * 0.15;
    float cs = cos(rot), sn = sin(rot);
    p = float2(p.x * cs - p.y * sn, p.x * sn + p.y * cs);

    float r = length(p);
    float ang = atan2(p.y, p.x);

    // k-sector kaleidoscope fold
    float k = 6.0 + floor(U.roll0 * 6.0) * 2.0;      // even, 6..16
    float sector = TAU_A / k;
    float a = fmod(ang + TAU_A, sector);             // 0..sector
    a = abs(a - sector * 0.5);                        // mirror -> kaleidoscope
    float an = a / (sector * 0.5);                    // 0..1 across the mirrored wedge

    // phi-folded petal rings — the infinite radius brought home
    float rr = phiFold_a(r * 2.4);
    float ringPhase = rr * 3.0 - r * 2.5;
    float ringField = 0.5 + 0.5 * cos(ringPhase);
    float petalA = 0.5 + 0.5 * cos(an * PI_A);
    float petal = pow(ringField * petalA, 1.4);

    // five-colour hard-quantized palette: chord + darkened variants
    float3 pal0 = U.colA.rgb;
    float3 pal1 = U.colB.rgb;
    float3 pal2 = U.colC.rgb;
    float3 pal3 = U.colA.rgb * 0.35;                  // darkened root
    float3 pal4 = U.colC.rgb * 0.50;                  // darkened highlight

    float ringIdx = floor(ringPhase + 8.0);           // integer ring id
    float sel = fract(ringIdx * 0.31718 + floor(an * 2.0) * 0.5);
    int idx = clamp(int(floor(sel * 5.0)), 0, 4);
    float3 cellCol;
    if      (idx == 0) cellCol = pal0;
    else if (idx == 1) cellCol = pal1;
    else if (idx == 2) cellCol = pal2;
    else if (idx == 3) cellCol = pal3;
    else               cellCol = pal4;

    // the sector wears its spectrum band
    // mirrored round the circle, so the negative x axis is not a seam
    float amp = band64_a(spectrum, abs(ang) / PI_A);
    cellCol *= (0.6 + 0.7 * amp);

    // dark seams: between rings and along the mirror fold — bands read as bands
    float ringF = fract(ringPhase);
    float rseam = smoothstep(0.0, 0.09, ringF) * smoothstep(1.0, 0.91, ringF);
    float mseam = smoothstep(0.0, 0.06, an);
    float body = petal * rseam * mseam;

    float3 col = cellCol * body * (0.40 + 0.45 * U.mid);

    // tip lamps at the petal ends answer the onset (a bright core -> INK budget)
    float tipR = 0.62;
    float tip = exp(-(r - tipR) * (r - tipR) * 60.0) * pow(petalA, 3.0);
    col += U.colC.rgb * tip * (0.15 + 0.90 * U.onsetEnv) * (0.4 + 0.9 * U.white);

    // faint hub swell on the bass
    col += U.colB.rgb * exp(-r * r * 22.0) * (0.12 + 0.30 * U.bass);

    // the void sky under the dark seams
    col += starLayer_a(uv) * mix(float3(0.7), U.colC.rgb, 0.5) * (1.0 - smoothstep(0.0, 0.9, petal));

    col += (hash21_a(pos.xy) - 0.5) * 0.004;
    return float4(govern_a(VOID_A + max(col, float3(0.0))), 1.0);
}
